name: Deploy to staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write  # Allows pushing to the repository, needed for the deployment to gh-pages
  pages: write     # Allows managing GitHub Pages
  actions: read    # Allows reading other GitHub Actions in the repository
  id-token: write  # Required for OIDC token-based authentication if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Set the REPOSITORY_URL_SITE environment variable
      run: echo "REPOSITORY_URL_SITE=https://github.com/$GITHUB_REPOSITORY" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install

    - name: Install additional dependencies
      run: |
        gem install rexml

    - name: Build the site
      run: |
        bundle exec jekyll build --baseurl=/${{ env.GITHUB_REPOSITORY_NAME_PART }}

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _site
        CLEAN: true